# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title_left    : "brew"
title_right   : "kode" # default: ""
description   : "checkout whats brewing"
cover         : "" # image uri like logo/cover image for site seo
baseurl	      : ""
url	      : "https://brewkode.com"
permalink     : /blog/:year/:month/:day/:title/

twitter_username  : brewkode
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
postshare_enabled : false
ga_tracker_id     : "UA-132274145-1"

github: [metadata]

markdown: kramdown

author:
  name     : "Sriram Ramachandrasekaran"

# Sass configuration
sass:
  sass_dir  : scss
  style     : compressed # expanded

plugins:
  - jekyll-paginate


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]

