# Site settings
title_left    : "brew"
title_right   : "kode" # default: ""
cover         : "" # image uri like logo/cover image for site seo

twitter_username  : "brewkode"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
postshare_enabled : false

remote_theme: heiswayi/thinkspace

author:
  name     : "Sriram Ramachandrasekaran"

